import { useEffect, useRef, useState } from 'react';
import { Bell, Building2, CreditCard, LogOut, Menu, Search, Settings, UserRound, X } from 'lucide-react';
import { masterRequest, queryString } from './api';
import { useDebounced } from './hooks';
import { fieldClass } from './components/MasterUI';
import type { Invoice, Plan, SessionResponse, Tenant } from './types';
interface SearchGroups { tenants: Tenant[]; accounts: Array<{ _id: string; name: string; email: string }>; invoices: Invoice[]; plans: Plan[] }
interface Props { path: string; account: SessionResponse['account']; attention: number; navigate: (path: string) => void; openMenu: () => void; logout: () => void }
const titles: Record<string, string> = { dashboard: 'Visão geral', lojas: 'Lojas', planos: 'Planos', assinaturas: 'Assinaturas', financeiro: 'Financeiro', acessos: 'Acessos', relatorios: 'Relatórios', atividades: 'Atividades', configuracoes: 'Configurações' };

export default function MasterTopbar({ path, account, attention, navigate, openMenu, logout }: Props) {
  const segment = path.split('/')[2] || 'dashboard'; const [openSearch, setOpenSearch] = useState(false); const [query, setQuery] = useState(''); const [results, setResults] = useState<SearchGroups | null>(null); const debounced = useDebounced(query); const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setOpenSearch(true); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []);
  useEffect(() => { if (openSearch) window.setTimeout(() => inputRef.current?.focus(), 30); }, [openSearch]);
  useEffect(() => { if (debounced.trim().length < 2) { setResults(null); return; } masterRequest<{ success: true; groups: SearchGroups }>(`/search${queryString({ q: debounced })}`).then((response) => setResults(response.groups)).catch(() => setResults(null)); }, [debounced]);
  const go = (target: string) => { setOpenSearch(false); setQuery(''); navigate(target); };
  return <><header className="sticky top-0 z-40 flex h-[72px] items-center gap-3 border-b border-slate-800 bg-slate-950/90 px-4 backdrop-blur-xl md:px-6"><button onClick={openMenu} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-800 text-slate-400 hover:text-white lg:hidden" aria-label="Abrir menu"><Menu className="h-5 w-5"/></button><div className="min-w-0 flex-1"><p className="text-[11px] text-slate-500">Master / {titles[segment] || 'Detalhe'}</p><h2 className="truncate text-base font-semibold text-white">{titles[segment] || 'Detalhe da loja'}</h2></div><button onClick={() => setOpenSearch(true)} className="hidden h-10 w-full max-w-sm items-center gap-3 rounded-xl border border-slate-800 bg-slate-900 px-3 text-left text-sm text-slate-500 hover:border-slate-700 md:flex"><Search className="h-4 w-4"/><span className="flex-1">Buscar lojas, faturas, acessos...</span><kbd className="rounded border border-slate-700 px-1.5 py-0.5 text-[10px]">Ctrl K</kbd></button><button onClick={() => navigate('/master/dashboard')} className="relative grid h-10 w-10 place-items-center rounded-xl border border-slate-800 text-slate-400 hover:text-white" title="Central de atenção"><Bell className="h-5 w-5"/>{attention > 0 && <span className="absolute -right-1 -top-1 min-w-5 rounded-full bg-amber-400 px-1 text-center text-[10px] font-bold leading-5 text-slate-950">{attention}</span>}</button><details className="relative"><summary className="flex h-10 list-none items-center gap-2 rounded-xl border border-slate-800 px-2 text-slate-300 hover:border-slate-700"><span className="grid h-7 w-7 place-items-center rounded-lg bg-slate-800"><UserRound className="h-4 w-4"/></span><span className="hidden max-w-28 truncate text-xs sm:block">{account.name}</span></summary><div className="absolute right-0 top-12 w-56 overflow-hidden rounded-xl border border-slate-700 bg-slate-900 shadow-2xl"><div className="border-b border-slate-800 p-3"><p className="truncate text-sm font-medium text-white">{account.name}</p><p className="truncate text-xs text-slate-500">{account.email}</p></div><button onClick={() => navigate('/master/configuracoes')} className="flex w-full items-center gap-2 px-3 py-2.5 text-sm text-slate-300 hover:bg-slate-800"><Settings className="h-4 w-4"/>Configurações</button><button onClick={logout} className="flex w-full items-center gap-2 px-3 py-2.5 text-sm text-red-300 hover:bg-red-500/10"><LogOut className="h-4 w-4"/>Sair</button></div></details></header>
    {openSearch && <div className="fixed inset-0 z-[90] bg-slate-950/80 p-3 pt-[8vh] backdrop-blur-sm" onClick={() => setOpenSearch(false)}><section className="mx-auto max-h-[78vh] max-w-2xl overflow-hidden rounded-2xl border border-slate-700 bg-slate-900 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-center gap-3 border-b border-slate-800 p-4"><Search className="h-5 w-5 text-emerald-400"/><input ref={inputRef} value={query} onChange={(event) => setQuery(event.target.value)} className={`${fieldClass} border-0 bg-transparent px-0 focus:ring-0`} placeholder="Digite pelo menos 2 caracteres..."/><button onClick={() => setOpenSearch(false)} className="text-slate-500 hover:text-white"><X className="h-5 w-5"/></button></div><div className="max-h-[62vh] overflow-y-auto p-3">{!results && <p className="p-6 text-center text-sm text-slate-500">Busque por loja, responsável, fatura ou plano.</p>}{results && <div className="space-y-4">{results.tenants.length > 0 && <SearchGroup title="Lojas" icon={<Building2 className="h-4 w-4"/>}>{results.tenants.map((item) => <SearchItem key={item._id} title={item.displayName} detail={`/${item.slug}`} onClick={() => go(`/master/lojas/${item._id}`)}/>)}</SearchGroup>}{results.accounts.length > 0 && <SearchGroup title="Acessos" icon={<UserRound className="h-4 w-4"/>}>{results.accounts.map((item) => <SearchItem key={item._id} title={item.name} detail={item.email} onClick={() => go('/master/acessos')}/>)}</SearchGroup>}{results.invoices.length > 0 && <SearchGroup title="Faturas" icon={<CreditCard className="h-4 w-4"/>}>{results.invoices.map((item) => <SearchItem key={item._id} title={item.receiptReference || item._id.slice(-8)} detail={item.status} onClick={() => go('/master/financeiro')}/>)}</SearchGroup>}{results.plans.length > 0 && <SearchGroup title="Planos" icon={<CreditCard className="h-4 w-4"/>}>{results.plans.map((item) => <SearchItem key={item._id} title={item.name} detail={item.code} onClick={() => go('/master/planos')}/>)}</SearchGroup>}{Object.values(results).every((items) => items.length === 0) && <p className="p-6 text-center text-sm text-slate-500">Nenhum resultado encontrado.</p>}</div>}</div></section></div>}
  </>;
}
function SearchGroup({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <div><p className="flex items-center gap-2 px-2 text-xs font-semibold uppercase tracking-wider text-slate-500">{icon}{title}</p><div className="mt-2 space-y-1">{children}</div></div>; }
function SearchItem({ title, detail, onClick }: { title: string; detail: string; onClick: () => void }) { return <button onClick={onClick} className="flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left hover:bg-slate-800"><span className="text-sm font-medium text-slate-200">{title}</span><span className="text-xs text-slate-500">{detail}</span></button>; }
