import { Activity, BarChart3, Building2, ChevronLeft, ChevronRight, CreditCard, FileText, Gauge, Layers3, ReceiptText, Settings, ShieldCheck, Users, X } from 'lucide-react';

const entries = [
  { path: '/master/dashboard', label: 'Visão geral', icon: Gauge }, { path: '/master/lojas', label: 'Lojas', icon: Building2 },
  { path: '/master/planos', label: 'Planos', icon: Layers3 }, { path: '/master/assinaturas', label: 'Assinaturas', icon: CreditCard },
  { path: '/master/financeiro', label: 'Financeiro', icon: ReceiptText }, { path: '/master/acessos', label: 'Acessos', icon: Users },
  { path: '/master/relatorios', label: 'Relatórios', icon: BarChart3 }, { path: '/master/atividades', label: 'Atividades', icon: Activity },
  { path: '/master/configuracoes', label: 'Configurações', icon: Settings },
];
interface Props { path: string; collapsed: boolean; mobileOpen: boolean; platformName: string; navigate: (path: string) => void; onCollapse: () => void; onClose: () => void }

export default function MasterSidebar({ path, collapsed, mobileOpen, platformName, navigate, onCollapse, onClose }: Props) {
  const content = <div className="flex h-full flex-col"><div className={`flex h-[72px] items-center border-b border-slate-800 ${collapsed ? 'justify-center px-3' : 'justify-between px-5'}`}><button onClick={() => navigate('/master/dashboard')} className="flex min-w-0 items-center gap-3 text-left"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-emerald-400 text-slate-950"><ShieldCheck className="h-5 w-5"/></span>{!collapsed && <span className="min-w-0"><strong className="block truncate text-sm text-white">{platformName}</strong><small className="text-[11px] text-slate-500">Admin Master</small></span>}</button><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-lg text-slate-400 hover:bg-slate-800 lg:hidden" aria-label="Fechar menu"><X className="h-5 w-5"/></button></div><nav className="flex-1 space-y-1 overflow-y-auto p-3" aria-label="Navegação principal">{entries.map((entry) => { const active = path === entry.path || (entry.path === '/master/lojas' && path.startsWith('/master/lojas/')); const Icon = entry.icon; return <button key={entry.path} title={collapsed ? entry.label : undefined} onClick={() => { navigate(entry.path); onClose(); }} className={`flex h-11 w-full items-center rounded-xl text-sm font-medium transition ${collapsed ? 'justify-center' : 'gap-3 px-3'} ${active ? 'bg-emerald-400/10 text-emerald-300 ring-1 ring-inset ring-emerald-400/15' : 'text-slate-400 hover:bg-slate-800/70 hover:text-white'}`}><Icon className="h-[18px] w-[18px] shrink-0"/>{!collapsed && <span>{entry.label}</span>}</button>; })}</nav><div className="border-t border-slate-800 p-3"><div className={`mb-3 rounded-xl border border-slate-800 bg-slate-950/70 p-3 ${collapsed ? 'hidden' : ''}`}><div className="flex items-center gap-2 text-xs font-medium text-emerald-300"><FileText className="h-4 w-4"/>Billing manual</div><p className="mt-1 text-[11px] leading-4 text-slate-500">Sem cobrança automática nesta fase.</p></div><button onClick={onCollapse} className="hidden h-10 w-full items-center justify-center gap-2 rounded-xl text-xs text-slate-500 hover:bg-slate-800 hover:text-white lg:flex">{collapsed ? <ChevronRight className="h-4 w-4"/> : <><ChevronLeft className="h-4 w-4"/>Recolher menu</>}</button></div></div>;
  return <><aside className={`fixed inset-y-0 left-0 z-50 hidden border-r border-slate-800 bg-slate-900 transition-[width] duration-200 lg:block ${collapsed ? 'w-[72px]' : 'w-64'}`}>{content}</aside>{mobileOpen && <div className="fixed inset-0 z-[70] bg-slate-950/75 backdrop-blur-sm lg:hidden" onClick={onClose}><aside className="h-full w-[min(310px,88vw)] border-r border-slate-800 bg-slate-900" onClick={(event) => event.stopPropagation()}>{content}</aside></div>}</>;
}
