import { AlertCircle, Check, ChevronLeft, ChevronRight, LoaderCircle, X } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import type { Pagination, ToastMessage } from '../types';
import { statusLabels, statusTones } from '../utils';

export const fieldClass = 'h-10 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm text-slate-100 outline-none transition placeholder:text-slate-600 focus:border-[var(--pv-primary)] focus:ring-2 focus:ring-[color:var(--pv-primary)]/20 disabled:opacity-50';
export const buttonPrimary = 'inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-[var(--pv-accent)] px-4 text-sm font-semibold text-[var(--pv-dark)] transition hover:brightness-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--pv-accent)] disabled:cursor-not-allowed disabled:opacity-50';
export const buttonSecondary = 'inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-slate-700 bg-slate-900 px-4 text-sm font-medium text-slate-200 transition hover:border-slate-600 hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--pv-primary)] disabled:opacity-50';

export function StatusBadge({ status }: { status: string }) { return <span className={`inline-flex whitespace-nowrap rounded-full border px-2.5 py-1 text-[11px] font-semibold ${statusTones[status] || statusTones.archived}`}>{statusLabels[status as keyof typeof statusLabels] || status}</span>; }
export function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-800 bg-slate-900/80 ${className}`}>{children}</section>; }
export function PageHeader({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description?: string; actions?: ReactNode }) { return <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div>{eyebrow && <p className="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-[var(--pv-accent)]">{eyebrow}</p>}<h1 className="text-2xl font-bold tracking-tight text-white md:text-3xl">{title}</h1>{description && <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{description}</p>}</div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</header>; }
export function KpiCard({ label, value, hint, icon }: { label: string; value: string; hint?: string; icon?: ReactNode }) { return <Card className="p-5"><div className="flex items-start justify-between"><p className="text-sm text-slate-400">{label}</p><span className="text-[var(--pv-accent)]">{icon}</span></div><strong className="mt-3 block text-2xl font-bold tabular-nums text-white">{value}</strong>{hint && <p className="mt-2 text-xs text-slate-500">{hint}</p>}</Card>; }
export function LoadingState({ rows = 4 }: { rows?: number }) { return <div className="space-y-3" aria-label="Carregando">{Array.from({ length: rows }, (_, index) => <div key={index} className="h-16 animate-pulse rounded-xl bg-slate-800/80" />)}</div>; }
export function EmptyState({ title = 'Nenhum resultado', description = 'Não há dados para os filtros selecionados.', action }: { title?: string; description?: string; action?: ReactNode }) { return <div className="grid min-h-52 place-items-center p-8 text-center"><div><div className="mx-auto grid h-11 w-11 place-items-center rounded-xl bg-slate-800 text-slate-400"><Check className="h-5 w-5" /></div><h3 className="mt-4 font-semibold text-white">{title}</h3><p className="mt-1 max-w-sm text-sm text-slate-400">{description}</p>{action && <div className="mt-4">{action}</div>}</div></div>; }
export function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div className="rounded-xl border border-red-500/20 bg-red-500/10 p-5"><div className="flex gap-3"><AlertCircle className="h-5 w-5 shrink-0 text-red-300"/><div><p className="font-medium text-red-200">Não foi possível carregar</p><p className="mt-1 text-sm text-red-300/80">{message}</p><button onClick={retry} className="mt-3 text-sm font-semibold text-red-200 underline">Tentar novamente</button></div></div></div>; }
export function TableShell({ children }: { children: ReactNode }) { return <Card className="overflow-hidden"><div className="overflow-x-auto">{children}</div></Card>; }
export function PaginationBar({ pagination, onPage, onLimit }: { pagination: Pagination; onPage: (page: number) => void; onLimit?: (limit: number) => void }) { return <div className="flex flex-col gap-3 border-t border-slate-800 px-4 py-3 text-sm text-slate-400 sm:flex-row sm:items-center sm:justify-between"><span>{pagination.total} resultado(s) · página {pagination.page} de {pagination.pages}</span><div className="flex items-center gap-2">{onLimit && <select value={pagination.limit} onChange={(event) => onLimit(Number(event.target.value))} className={`${fieldClass} w-24`} aria-label="Itens por página"><option value="10">10</option><option value="25">25</option><option value="50">50</option></select>}<button className={buttonSecondary} disabled={pagination.page <= 1} onClick={() => onPage(pagination.page - 1)} aria-label="Página anterior"><ChevronLeft className="h-4 w-4"/></button><button className={buttonSecondary} disabled={pagination.page >= pagination.pages} onClick={() => onPage(pagination.page + 1)} aria-label="Próxima página"><ChevronRight className="h-4 w-4"/></button></div></div>; }

export function Modal({ title, description, open, onClose, children, footer }: { title: string; description?: string; open: boolean; onClose: () => void; children: ReactNode; footer?: ReactNode }) {
  if (!open) return null;
  return <div className="fixed inset-0 z-[80] grid place-items-end bg-slate-950/80 p-0 backdrop-blur-sm sm:place-items-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="master-modal-title"><div className="flex max-h-[92dvh] w-full max-w-xl flex-col rounded-t-2xl border border-slate-700 bg-slate-900 shadow-2xl sm:rounded-2xl"><header className="flex items-start justify-between border-b border-slate-800 px-5 py-4"><div><h2 id="master-modal-title" className="font-semibold text-white">{title}</h2>{description && <p className="mt-1 text-sm text-slate-400">{description}</p>}</div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-lg text-slate-400 hover:bg-slate-800 hover:text-white" aria-label="Fechar"><X className="h-5 w-5"/></button></header><div className="min-h-0 overflow-y-auto p-5">{children}</div>{footer && <footer className="flex justify-end gap-2 border-t border-slate-800 p-4">{footer}</footer>}</div></div>;
}
export function ConfirmReasonModal({ open, title, description, confirmLabel, busy, onClose, onConfirm }: { open: boolean; title: string; description: string; confirmLabel: string; busy?: boolean; onClose: () => void; onConfirm: (reason: string) => void }) {
  const [reason, setReason] = useState('');
  const close = () => { setReason(''); onClose(); };
  return <Modal open={open} onClose={close} title={title} description={description} footer={<><button className={buttonSecondary} onClick={close}>Voltar</button><button className={buttonPrimary} disabled={busy || reason.trim().length < 5} onClick={() => onConfirm(reason)}>{busy && <LoaderCircle className="h-4 w-4 animate-spin"/>}{confirmLabel}</button></>}><label className="text-sm font-medium text-slate-300">Motivo<input className={`${fieldClass} mt-2`} minLength={5} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Informe um motivo com pelo menos 5 caracteres" /></label></Modal>;
}
export function Toasts({ items }: { items: ToastMessage[] }) { return <div className="fixed right-4 top-4 z-[100] flex w-[min(360px,calc(100%-2rem))] flex-col gap-2">{items.map((item) => <div key={item.id} className={`rounded-xl border px-4 py-3 text-sm shadow-xl ${item.tone === 'error' ? 'border-red-500/30 bg-red-950 text-red-100' : item.tone === 'success' ? 'border-emerald-500/30 bg-emerald-950 text-emerald-100' : 'border-slate-700 bg-slate-900 text-slate-100'}`}>{item.message}</div>)}</div>; }

export function MiniAreaChart({ points, valueKey, color = '#f8a838' }: { points: readonly unknown[]; valueKey: string; color?: string }) {
  const values = points.map((point) => Number((point as Record<string, unknown>)[valueKey] || 0)); const max = Math.max(...values, 1); const width = 720; const height = 190;
  const coordinates = values.map((value, index) => `${values.length <= 1 ? width / 2 : index * width / (values.length - 1)},${height - (value / max) * (height - 24)}`).join(' ');
  if (!points.length) return <EmptyState title="Sem série no período" description="Ainda não há movimentação suficiente para este gráfico." />;
  return <div className="overflow-hidden"><svg viewBox={`0 0 ${width} ${height}`} className="h-48 w-full" role="img" aria-label="Gráfico do período"><defs><linearGradient id={`gradient-${valueKey}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity=".28"/><stop offset="1" stopColor={color} stopOpacity="0"/></linearGradient></defs><path d={`M ${coordinates} L ${width},${height} L 0,${height} Z`} fill={`url(#gradient-${valueKey})`}/><polyline points={coordinates} fill="none" stroke={color} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg></div>;
}
