import React, { useEffect, useMemo, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, BarChart3, Clock3, Download, Minus, Package, Printer, RefreshCw, ShoppingBag, Tags, TrendingUp, WalletCards } from 'lucide-react';
import { paymentMethodLabel } from '../lib/paymentMethods';
import { downloadBlob } from '../lib/download';
import { useTenantAdminApi } from './tenant-admin/TenantAdminContext';
import { useToast } from './Toast';

const money = (value: unknown) => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const localDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;

function presetDates(id: string) {
  const to = new Date(); const from = new Date(to);
  if (id === 'yesterday') { from.setDate(from.getDate() - 1); to.setDate(to.getDate() - 1); }
  if (id === '7days') from.setDate(from.getDate() - 6);
  if (id === '30days') from.setDate(from.getDate() - 29);
  if (id === 'month') from.setDate(1);
  return { from: localDate(from), to: localDate(to) };
}

export default function AdminReports() {
  const api = useTenantAdminApi(); const { showToast } = useToast();
  const [tab, setTab] = useState<'overview' | 'products' | 'operation'>('overview');
  const [preset, setPreset] = useState('30days'); const [period, setPeriod] = useState(presetDates('30days'));
  const [data, setData] = useState<any>({ summary: null, products: null, operation: null, settings: null });
  const [loading, setLoading] = useState(true); const [exporting, setExporting] = useState(''); const [error, setError] = useState('');

  const load = async () => {
    setLoading(true); setError('');
    try {
      const [summary, products, operation, settings] = await Promise.all([api.getReportSummary(period.from, period.to), api.getProductReport(period.from, period.to), api.getOperationReport(period.from, period.to), api.getSettings()]);
      setData({ summary, products, operation, settings: settings.settings });
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Nao foi possivel carregar os relatorios.'); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, []);
  const setPresetPeriod = (id: string) => { setPreset(id); setPeriod(presetDates(id)); };
  const maxRevenue = useMemo(() => Math.max(1, ...(data.summary?.byDay || []).map((day: any) => Number(day.revenue || 0))), [data.summary]);
  const maxHour = useMemo(() => Math.max(1, ...(data.operation?.byHour || []).map((hour: any) => Number(hour.orders || 0))), [data.operation]);

  const exportCsv = async (kind: 'summary' | 'products' | 'categories') => {
    setExporting(kind);
    try { downloadBlob(await api.exportReport(kind, period.from, period.to), `${kind}-${period.from}-a-${period.to}.csv`); }
    catch (reason) { showToast(reason instanceof Error ? reason.message : 'Erro ao exportar relatorio.', 'error'); }
    finally { setExporting(''); }
  };

  return <div className="space-y-5">
    <section className="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm sm:p-6 admin-no-print"><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-600">Fechamento operacional</p><h2 className="mt-1 text-2xl font-black text-gray-900">Quanto vendi e como recebi?</h2><p className="mt-1 text-sm text-gray-500">Compare periodos, exporte seus dados e gere um fechamento apresentavel.</p></div><div className="flex flex-wrap gap-2">{[['today','Hoje'],['yesterday','Ontem'],['7days','7 dias'],['30days','30 dias'],['month','Este mes']].map(([id,label]) => <button key={id} onClick={() => setPresetPeriod(id)} className={`h-9 rounded-lg px-3 text-xs font-bold ${preset === id ? 'bg-emerald-600 text-white' : 'border border-gray-200 text-gray-600'}`}>{label}</button>)}</div></div><div className="mt-5 flex flex-col gap-3 border-t pt-5 sm:flex-row sm:items-end"><label className="text-xs font-semibold text-gray-600">De<input type="date" value={period.from} onChange={(event) => { setPreset('custom'); setPeriod({ ...period, from: event.target.value }); }} className="mt-1 block h-10 rounded-lg border px-3 text-sm" /></label><label className="text-xs font-semibold text-gray-600">Ate<input type="date" value={period.to} onChange={(event) => { setPreset('custom'); setPeriod({ ...period, to: event.target.value }); }} className="mt-1 block h-10 rounded-lg border px-3 text-sm" /></label><button onClick={load} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-gray-900 px-4 text-sm font-bold text-white"><RefreshCw className="h-4 w-4" />Atualizar</button><div className="sm:ml-auto flex flex-wrap gap-2"><button onClick={() => exportCsv(tab === 'overview' ? 'summary' : 'products')} disabled={Boolean(exporting)} className="inline-flex h-10 items-center gap-2 rounded-lg border px-3 text-sm font-bold disabled:opacity-50"><Download className="h-4 w-4" />{exporting ? 'Exportando...' : tab === 'overview' ? 'Exportar fechamento' : 'Exportar produtos'}</button>{tab === 'products' && <button onClick={() => exportCsv('categories')} disabled={Boolean(exporting)} className="inline-flex h-10 items-center gap-2 rounded-lg border px-3 text-sm font-bold"><Download className="h-4 w-4" />Categorias</button>}{tab === 'overview' && <button onClick={() => window.print()} className="inline-flex h-10 items-center gap-2 rounded-lg bg-emerald-600 px-3 text-sm font-bold text-white"><Printer className="h-4 w-4" />Imprimir / PDF</button>}</div></div></section>
    <div className="admin-no-print flex gap-2 overflow-x-auto rounded-xl border bg-white p-1 shadow-sm">{[['overview','Visao geral',WalletCards],['products','Produtos',Package],['operation','Operacao',Clock3]].map(([id,label,Icon]: any) => <button key={id} onClick={() => setTab(id)} className={`inline-flex min-w-36 flex-1 items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-bold ${tab === id ? 'bg-emerald-600 text-white' : 'text-gray-600'}`}><Icon className="h-4 w-4" />{label}</button>)}</div>
    {error && <div className="admin-no-print rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <div className="admin-no-print">{loading ? <div className="rounded-2xl border bg-white p-12 text-center text-sm text-gray-500">Calculando indicadores...</div> : <>{tab === 'overview' && data.summary && <Overview data={data.summary} maxRevenue={maxRevenue} />}{tab === 'products' && data.products && <ProductsReport data={data.products} />}{tab === 'operation' && data.operation && <OperationReport data={data.operation} maxHour={maxHour} />}</>}</div>
    {!loading && data.summary && <SalesPrintReport summary={data.summary} products={data.products} settings={data.settings} />}
  </div>;
}

function MetricCard({ Icon, label, value, comparison, lowerIsBetter = false, helper }: any) { return <div className="rounded-2xl border bg-white p-5 shadow-sm"><Icon className="h-5 w-5 text-emerald-600" /><p className="mt-4 text-sm text-gray-500">{label}</p><p className="mt-1 text-2xl font-black text-gray-900">{value}</p>{comparison && <Comparison value={comparison} lowerIsBetter={lowerIsBetter} />}{helper && <p className="mt-1 text-xs text-gray-400">{helper}</p>}</div>; }
function Comparison({ value }: { value: any; lowerIsBetter?: boolean }) { if (!value || value.state === 'unavailable') return <p className="mt-2 text-xs text-gray-400">Sem comparacao disponivel</p>; if (value.state === 'new') return <p className={`mt-2 text-xs font-bold ${value.favorable ? 'text-emerald-600' : 'text-amber-600'}`}>Novo no periodo</p>; const percent = Number(value.percent || 0); const Icon = percent > 0 ? ArrowUpRight : percent < 0 ? ArrowDownRight : Minus; return <p className={`mt-2 flex items-center gap-1 text-xs font-bold ${value.favorable === true ? 'text-emerald-600' : value.favorable === false ? 'text-red-600' : 'text-gray-500'}`}><Icon className="h-3.5 w-3.5" />{Math.abs(percent).toFixed(1).replace('.', ',')}% vs periodo anterior</p>; }

function Overview({ data, maxRevenue }: any) { return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard Icon={WalletCards} label="Faturamento" value={money(data.metrics.revenue)} comparison={data.comparisons?.revenue} /><MetricCard Icon={ShoppingBag} label="Pedidos validos" value={data.metrics.validOrders} comparison={data.comparisons?.validOrders} /><MetricCard Icon={TrendingUp} label="Ticket medio" value={money(data.metrics.averageOrder)} comparison={data.comparisons?.averageOrder} /><MetricCard Icon={BarChart3} label="Cancelamentos" value={data.metrics.cancelled} comparison={data.comparisons?.cancelled} lowerIsBetter /><MetricCard Icon={ShoppingBag} label="Novos clientes" value={data.metrics.newCustomers || 0} comparison={data.comparisons?.newCustomers} /></div><p className="rounded-xl bg-gray-50 p-3 text-xs text-gray-500">Comparando {data.period.from} a {data.period.to} com {data.period.previousFrom} a {data.period.previousTo}.</p><div className="grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><section className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Faturamento por dia</h3>{data.byDay.length ? <div className="mt-6 flex h-56 items-end gap-2 overflow-x-auto pb-2">{data.byDay.map((day: any) => <div key={day.date} className="flex min-w-12 flex-1 flex-col items-center justify-end gap-2"><span className="text-[10px] font-semibold text-gray-500">{money(day.revenue)}</span><div className="w-full max-w-12 rounded-t-lg bg-emerald-500" style={{ height: `${Math.max(6, Number(day.revenue || 0) / maxRevenue * 150)}px` }} /><span className="text-[10px] text-gray-400">{day.date.slice(5).split('-').reverse().join('/')}</span></div>)}</div> : <p className="mt-10 text-center text-sm text-gray-500">Nenhuma venda valida no periodo.</p>}</section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Como recebeu</h3><div className="mt-4 space-y-3">{data.payments.map((item: any) => <div key={item.method} className="flex justify-between rounded-xl bg-gray-50 p-3"><div><p className="text-sm font-bold">{paymentMethodLabel(item.method)}</p><p className="text-xs text-gray-400">{item.orders} pedido(s)</p></div><strong>{money(item.total)}</strong></div>)}{!data.payments.length && <p className="text-sm text-gray-500">Sem recebimentos.</p>}</div><div className="mt-5 space-y-2 border-t pt-4 text-sm"><div className="flex justify-between"><span>Descontos concedidos</span><strong>{money(data.metrics.discounts)}</strong></div><div className="flex justify-between"><span>Taxas de entrega</span><strong>{money(data.metrics.deliveryFees)}</strong></div></div></section></div></div>; }

function ProductsReport({ data }: any) { return <div className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]"><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="p-5"><h3 className="font-bold">Ranking de produtos</h3><p className="text-xs text-gray-500">Valores historicos gravados nos pedidos.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-gray-50 text-xs text-gray-500"><tr><th className="p-4">#</th><th className="p-4">Produto</th><th className="p-4">Categoria</th><th className="p-4 text-right">Unidades</th><th className="p-4 text-right">Faturamento</th></tr></thead><tbody className="divide-y">{data.products.map((item: any, index: number) => <tr key={`${item.productId}-${item.name}`}><td className="p-4 font-black text-gray-400">{index + 1}</td><td className="p-4 font-bold">{item.name}</td><td className="p-4 text-gray-500">{item.category}</td><td className="p-4 text-right">{item.units}</td><td className="p-4 text-right font-black">{money(item.revenue)}</td></tr>)}</tbody></table></div>{!data.products.length && <p className="p-10 text-center text-sm text-gray-500">Nenhum produto vendido.</p>}</section><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Tags className="h-5 w-5 text-emerald-600" /><h3 className="font-bold">Categorias</h3></div><div className="mt-5 space-y-4">{data.categories.map((item: any) => <div key={item.category}><div className="flex justify-between text-sm"><div><p className="font-bold">{item.category}</p><p className="text-xs text-gray-400">{item.units} item(ns)</p></div><div className="text-right"><strong>{money(item.revenue)}</strong><p className="text-xs text-gray-400">{Number(item.share).toFixed(1)}%</p></div></div><div className="mt-2 h-2 rounded-full bg-gray-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${Math.min(100, Number(item.share))}%` }} /></div></div>)}</div></section></div>; }

function OperationReport({ data, maxHour }: any) { const duration = (minutes: unknown, samples: number) => samples >= 2 && minutes != null ? `${minutes} min` : 'Dados insuficientes'; return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard Icon={Clock3} label="Ate iniciar preparo" value={duration(data.metrics.averageToPrepareMinutes, data.metrics.samples.start)} helper={`${data.metrics.samples.start} amostra(s)`} /><MetricCard Icon={Clock3} label="Tempo de preparo" value={duration(data.metrics.averagePreparationMinutes, data.metrics.samples.preparation)} helper={`${data.metrics.samples.preparation} amostra(s)`} /><MetricCard Icon={TrendingUp} label="Tempo total" value={duration(data.metrics.averageTotalMinutes, data.metrics.samples.total)} helper={`${data.metrics.samples.total} amostra(s)`} /><MetricCard Icon={ShoppingBag} label="Taxa de cancelamento" value={data.metrics.cancellationRate == null ? 'Dados insuficientes' : `${Number(data.metrics.cancellationRate).toFixed(1)}%`} /></div><div className="grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><section className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Pedidos por horario</h3>{data.byHour.length ? <div className="mt-6 flex h-56 items-end gap-2 overflow-x-auto pb-2">{data.byHour.map((item: any) => <div key={item.hour} className="flex min-w-12 flex-1 flex-col items-center justify-end gap-2"><span className="text-xs font-bold">{item.orders}</span><div className="w-full max-w-12 rounded-t-lg bg-blue-500" style={{ height: `${Math.max(6, Number(item.orders) / maxHour * 150)}px` }} /><span className="text-[10px] text-gray-400">{item.hour}</span></div>)}</div> : <p className="mt-10 text-center text-sm text-gray-500">Dados insuficientes.</p>}</section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Maior movimento</h3><div className="mt-5 space-y-3">{data.peakHours.map((item: any, index: number) => <div key={item.hour} className="flex justify-between rounded-xl bg-gray-50 p-4"><div><p className="text-xs font-bold text-gray-400">{index + 1}o horario</p><p className="text-lg font-black">{item.hour}</p></div><strong>{item.orders} pedido(s)</strong></div>)}{!data.peakHours.length && <p className="text-sm text-gray-500">Dados insuficientes.</p>}</div></section></div></div>; }

function SalesPrintReport({ summary, products, settings }: any) { return <article className="sales-print-report"><header className="print-header">{settings?.logo_url && <img src={settings.logo_url} alt="" />}<div><p className="print-eyebrow">FECHAMENTO DE VENDAS</p><h1>{settings?.nome_loja || 'Loja'}</h1><p>Periodo: {summary.period.from} a {summary.period.to}</p><p>Gerado em {new Date().toLocaleString('pt-BR')}</p></div></header><section className="print-metrics"><PrintMetric label="Faturamento" value={money(summary.metrics.revenue)} /><PrintMetric label="Pedidos" value={summary.metrics.validOrders} /><PrintMetric label="Ticket medio" value={money(summary.metrics.averageOrder)} /><PrintMetric label="Cancelamentos" value={summary.metrics.cancelled} /></section><div className="print-grid"><section><h2>Formas de pagamento</h2>{summary.payments.map((item: any) => <p key={item.method}><span>{paymentMethodLabel(item.method)}</span><strong>{money(item.total)}</strong></p>)}</section><section><h2>Resumo financeiro</h2><p><span>Taxas de entrega</span><strong>{money(summary.metrics.deliveryFees)}</strong></p><p><span>Descontos</span><strong>{money(summary.metrics.discounts)}</strong></p></section></div><div className="print-grid"><section><h2>Principais produtos</h2>{(products?.products || []).slice(0, 8).map((item: any) => <p key={`${item.productId}-${item.name}`}><span>{item.name} · {item.units} un.</span><strong>{money(item.revenue)}</strong></p>)}</section><section><h2>Principais categorias</h2>{(products?.categories || []).slice(0, 8).map((item: any) => <p key={item.category}><span>{item.category} · {Number(item.share).toFixed(1)}%</span><strong>{money(item.revenue)}</strong></p>)}</section></div>{summary.comparisons?.revenue && <footer>Comparativo: faturamento {summary.comparisons.revenue.percent == null ? 'sem comparacao disponivel' : `${Number(summary.comparisons.revenue.percent).toFixed(1)}%`} versus {summary.period.previousFrom} a {summary.period.previousTo}.</footer>}</article>; }
function PrintMetric({ label, value }: any) { return <div><span>{label}</span><strong>{value}</strong></div>; }
