import React, { useEffect, useState } from 'react';
import { Download, Gift, Loader2, Plus, Tag, Ticket, Trash2, X } from 'lucide-react';
import { useToast } from './Toast';
import { useTenantAdminApi } from './tenant-admin/TenantAdminContext';
import { downloadBlob } from '../lib/download';

const money = (value: unknown) => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const localDate = (value: Date) => `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`;
const inputClass = 'mt-1 h-11 w-full rounded-xl border border-gray-200 bg-gray-50 px-3 outline-none focus:border-emerald-500';

export default function AdminCoupons({ token }: { token: string; onUnauthorized: () => void }) {
  const api = useTenantAdminApi(); const { showToast } = useToast();
  const today = new Date(); const monthAgo = new Date(today); monthAgo.setDate(monthAgo.getDate() - 29);
  const [period] = useState({ from: localDate(monthAgo), to: localDate(today) });
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true); const [isAdding, setIsAdding] = useState(false); const [saving, setSaving] = useState(false); const [exporting, setExporting] = useState(false);
  const [form, setForm] = useState({ codigo: '', tipo: 'fixo', valor: '', minimo_pedido: 0, validade: '', usos_restantes: -1 });

  const load = async () => { setLoading(true); try { setReport(await api.getMarketingReport(period.from, period.to)); } catch (error) { showToast(error instanceof Error ? error.message : 'Erro ao carregar desempenho.', 'error'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [token]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await api.createCoupon(form); showToast('Cupom criado com sucesso.', 'success'); setForm({ codigo: '', tipo: 'fixo', valor: '', minimo_pedido: 0, validade: '', usos_restantes: -1 }); setIsAdding(false); await load(); } catch (error) { showToast(error instanceof Error ? error.message : 'Erro ao criar cupom.', 'error'); } finally { setSaving(false); } };
  const remove = async (id: string) => { if (!window.confirm('Excluir este cupom?')) return; try { await api.deleteCoupon(id); showToast('Cupom removido.', 'success'); await load(); } catch (error) { showToast(error instanceof Error ? error.message : 'Erro ao remover cupom.', 'error'); } };
  const exportCsv = async () => { setExporting(true); try { downloadBlob(await api.exportReport('marketing', period.from, period.to), `cupons-${period.from}-a-${period.to}.csv`); } catch (error) { showToast(error instanceof Error ? error.message : 'Erro ao exportar cupons.', 'error'); } finally { setExporting(false); } };

  if (loading) return <div className="p-10 text-center text-sm text-gray-500">Calculando desempenho de cupons e fidelidade...</div>;
  const coupons = report?.coupons || []; const loyalty = report?.loyalty || {};
  return <div className="space-y-4">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Ticket className="h-4 w-4 text-emerald-600" />Cupons e fidelidade</h2><p className="mt-0.5 text-xs text-gray-500">Resultado comercial dos ultimos 30 dias, sem estimar lucro.</p></div><div className="flex gap-2"><button onClick={exportCsv} disabled={exporting} className="inline-flex h-9 items-center gap-2 rounded-lg border px-3 text-xs font-semibold disabled:opacity-50"><Download className="h-3.5 w-3.5" />{exporting ? 'Exportando...' : 'Exportar cupons'}</button><button onClick={() => setIsAdding(true)} className="inline-flex h-9 items-center gap-2 rounded-lg bg-emerald-600 px-3 text-xs font-semibold text-white"><Plus className="h-3.5 w-3.5" />Novo cupom</button></div></div>

    <section className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><Gift className="h-4 w-4 text-emerald-600" /><h3 className="text-sm font-bold text-gray-900">Uso da fidelidade</h3></div><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Pontos gerados" value={loyalty.pointsGenerated || 0} /><Metric label="Pontos resgatados" value={loyalty.pointsRedeemed || 0} /><Metric label="Resgates" value={loyalty.redemptions || 0} /><Metric label="Clientes com saldo" value={loyalty.customersWithBalance || 0} /></div><div className="mt-3 grid gap-3 lg:grid-cols-2"><div className="rounded-lg bg-gray-50 p-3"><p className="text-xs font-bold">Clientes que ja resgataram</p><p className="mt-0.5 text-xl font-bold">{loyalty.customersWhoRedeemed || 0}</p>{loyalty.minimumReward && <p className="mt-0.5 text-[11px] text-gray-500">Menor recompensa: {loyalty.minimumReward} pontos</p>}</div><div className="rounded-lg bg-gray-50 p-3"><p className="text-xs font-bold">Valor equivalente dos resgates</p><p className="mt-0.5 text-xl font-bold">{loyalty.equivalentValue == null ? 'Dados insuficientes' : money(loyalty.equivalentValue)}</p><p className="mt-0.5 text-[11px] text-gray-500">Disponivel para pedidos com snapshot de resgate.</p></div></div>{loyalty.topRedeemedProducts?.length ? <div className="mt-3"><p className="text-xs font-bold">Produtos mais resgatados</p><div className="mt-1.5 grid gap-2 sm:grid-cols-2">{loyalty.topRedeemedProducts.map((item: any) => <div key={`${item.productId}-${item.name}`} className="flex justify-between rounded-lg border p-2.5 text-xs"><span>{item.name}</span><strong>{item.units} un.</strong></div>)}</div></div> : <p className="mt-3 rounded-lg border border-dashed p-2.5 text-xs text-gray-500">O ranking de produtos resgatados comeca a ser formado pelos novos pedidos.</p>}
      {loyalty.nearRewardCustomers?.length > 0 && <div className="mt-4"><p className="text-sm font-bold">Mais proximos da primeira recompensa</p><div className="mt-2 flex gap-2 overflow-x-auto">{loyalty.nearRewardCustomers.map((customer: any) => <span key={customer._id} className="shrink-0 rounded-full bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800">{customer.nome} · {customer.pontos} pts</span>)}</div></div>}
    </section>

    <section className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm"><div className="border-b p-4"><h3 className="text-sm font-bold">Desempenho dos cupons</h3><p className="mt-0.5 text-[11px] text-gray-500">Faturamento significa vendas dos pedidos com cupom, nao lucro.</p></div>{coupons.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-gray-50 text-xs text-gray-500"><tr><th className="p-3">Cupom</th><th className="p-3">Usos</th><th className="p-3">Clientes</th><th className="p-3">Vendas</th><th className="p-3">Descontos</th><th className="p-3">Ticket medio</th><th className="p-3">Ultimo uso</th><th className="p-3" /></tr></thead><tbody className="divide-y">{coupons.map((coupon: any) => <tr key={coupon._id}><td className="p-3"><div className="flex items-center gap-2"><Tag className="h-3.5 w-3.5 text-emerald-600" /><div><p className="font-bold">{coupon.codigo}</p><p className="text-xs text-gray-500">{coupon.tipo === 'porcentagem' ? `${coupon.valor}%` : money(coupon.valor)}</p></div></div></td><td className="p-3 font-semibold">{coupon.analytics?.uses || 0}</td><td className="p-3">{coupon.analytics?.customers || 0}</td><td className="p-3 font-semibold">{money(coupon.analytics?.revenue)}</td><td className="p-3">{money(coupon.analytics?.discounts)}</td><td className="p-3">{money(coupon.analytics?.averageTicket)}</td><td className="p-3">{coupon.analytics?.lastUsedAt ? new Date(coupon.analytics.lastUsedAt).toLocaleDateString('pt-BR') : 'Nunca usado'}</td><td className="p-3 text-right"><button aria-label={`Excluir cupom ${coupon.codigo}`} onClick={() => remove(coupon._id)} className="grid h-8 w-8 place-items-center rounded-lg text-red-500 hover:bg-red-50"><Trash2 className="h-3.5 w-3.5" /></button></td></tr>)}</tbody></table></div> : <div className="p-6 text-center text-sm text-gray-500">Nenhum cupom cadastrado.</div>}</section>

    {isAdding && <div className="fixed inset-0 z-50 grid place-items-center bg-gray-950/50 p-4" role="dialog" aria-modal="true"><form onSubmit={save} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-start justify-between"><div><h3 className="text-xl font-black">Novo cupom</h3><p className="text-sm text-gray-500">Defina a regra comercial do codigo.</p></div><button type="button" aria-label="Fechar" onClick={() => setIsAdding(false)} className="grid h-9 w-9 place-items-center rounded-full bg-gray-100"><X className="h-4 w-4" /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Codigo"><input required value={form.codigo} onChange={(event) => setForm({ ...form, codigo: event.target.value.toUpperCase() })} className={inputClass} /></Field><Field label="Tipo"><select value={form.tipo} onChange={(event) => setForm({ ...form, tipo: event.target.value })} className={inputClass}><option value="fixo">Valor fixo</option><option value="porcentagem">Porcentagem</option></select></Field><Field label="Valor"><input required type="number" min="0" step="0.01" value={form.valor} onChange={(event) => setForm({ ...form, valor: event.target.value })} className={inputClass} /></Field><Field label="Pedido minimo"><input type="number" min="0" step="0.01" value={form.minimo_pedido} onChange={(event) => setForm({ ...form, minimo_pedido: Number(event.target.value) })} className={inputClass} /></Field><Field label="Validade"><input type="date" value={form.validade} onChange={(event) => setForm({ ...form, validade: event.target.value })} className={inputClass} /></Field><Field label="Usos restantes (-1 = ilimitado)"><input type="number" min="-1" value={form.usos_restantes} onChange={(event) => setForm({ ...form, usos_restantes: Number(event.target.value) })} className={inputClass} /></Field></div><button disabled={saving} className="mt-6 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 font-bold text-white disabled:opacity-50">{saving && <Loader2 className="h-4 w-4 animate-spin" />}{saving ? 'Salvando...' : 'Criar cupom'}</button></form></div>}
  </div>;
}

function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <div className="rounded-lg bg-gray-50 p-2.5"><p className="text-[11px] text-gray-500">{label}</p><p className="mt-0.5 text-lg font-bold">{value}</p></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-semibold text-gray-700">{label}{children}</label>; }
