import { AlertTriangle, ArrowRight, Building2, CalendarClock, CircleDollarSign, ReceiptText, ShoppingBag, Store, TrendingUp, Users } from 'lucide-react';
import { useEffect } from 'react';
import { masterRequest, queryString } from '../api';
import { useRemote } from '../hooks';
import type { DashboardResponse, PeriodKey } from '../types';
import { integer, money, periodLabels, rangeForPeriod } from '../utils';
import { Card, EmptyState, ErrorState, KpiCard, LoadingState, MiniAreaChart, PageHeader, StatusBadge, buttonPrimary, buttonSecondary, fieldClass } from '../components/MasterUI';

export default function MasterOverview({ period, setPeriod, navigate, onAttention }: { period: PeriodKey; setPeriod: (period: PeriodKey) => void; navigate: (path: string) => void; onAttention: (count: number) => void }) {
  const range = rangeForPeriod(period); const remote = useRemote(() => masterRequest<DashboardResponse>(`/dashboard${queryString(range)}`), [period]); const data = remote.data;
  useEffect(() => { if (data) onAttention(data.kpis.trialsEndingSoon + data.attention.overdueInvoices.length + data.attention.stalledOnboarding.length); }, [data, onAttention]);
  const kpi = data?.kpis || {};
  return <div className="space-y-6"><PageHeader eyebrow="Cockpit executivo" title="Visão geral" description="Saúde comercial e operacional da plataforma, sem misturar o GMV das lojas com a receita SaaS." actions={<><select className={`${fieldClass} w-40`} value={period} onChange={(event) => setPeriod(event.target.value as PeriodKey)}>{Object.entries(periodLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className={buttonPrimary} onClick={() => navigate('/master/lojas')}>Gerenciar lojas<ArrowRight className="h-4 w-4"/></button></>}/>
    {remote.loading && !data ? <LoadingState rows={8}/> : remote.error ? <ErrorState message={remote.error} retry={remote.refresh}/> : data && <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Lojas ativas" value={integer(kpi.activeTenants)} hint={`${integer(kpi.totalTenants)} lojas no total`} icon={<Building2 className="h-5 w-5"/>}/><KpiCard label="Pedidos no período" value={integer(kpi.orders)} hint={`Ticket médio ${money(kpi.averageOrderCents)}`} icon={<ShoppingBag className="h-5 w-5"/>}/><KpiCard label="GMV das lojas" value={money(kpi.gmvCents)} hint="Soma dos pedidos válidos" icon={<TrendingUp className="h-5 w-5"/>}/><KpiCard label="Receita SaaS recebida" value={money(kpi.paidRevenueCents)} hint={`${money(kpi.pendingRevenueCents)} pendente`} icon={<CircleDollarSign className="h-5 w-5"/>}/><KpiCard label="MRR atual" value={money(kpi.mrrCents)} hint={`ARR projetado ${money(kpi.arrCents)}`} icon={<ReceiptText className="h-5 w-5"/>}/><KpiCard label="Trial" value={integer(kpi.trialTenants)} hint={`${integer(kpi.trialsEndingSoon)} vencendo em 7 dias`} icon={<CalendarClock className="h-5 w-5"/>}/><KpiCard label="Onboarding" value={integer(kpi.onboardingTenants)} hint={`${integer(kpi.newTenants)} novas no período`} icon={<Store className="h-5 w-5"/>}/><KpiCard label="Receita vencida" value={money(kpi.overdueRevenueCents)} hint={`${integer(kpi.pastDueTenants)} lojas inadimplentes`} icon={<AlertTriangle className="h-5 w-5"/>}/></section>
      <section className="grid gap-4 xl:grid-cols-2"><Card className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-white">Pedidos e GMV</h2><p className="mt-1 text-xs text-slate-500">Movimentação diária das lojas no período</p></div><span className="text-xs text-slate-500">{periodLabels[period]}</span></div><MiniAreaChart points={data.orderSeries} valueKey="gmvCents"/></Card><Card className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-white">Receita SaaS</h2><p className="mt-1 text-xs text-slate-500">Faturas pagas da plataforma, sem incluir GMV</p></div><span className="text-xs text-emerald-300">{money(kpi.paidRevenueCents)}</span></div><MiniAreaChart points={data.revenueSeries} valueKey="paidCents" color="#22d3ee"/></Card></section>
      <section className="grid gap-4 xl:grid-cols-[1fr_1.5fr]"><Card className="p-5"><h2 className="font-semibold text-white">Distribuição das lojas</h2><div className="mt-5 space-y-3">{data.tenantStatusDistribution.map((item) => <div key={item.status} className="flex items-center gap-3"><StatusBadge status={item.status}/><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-emerald-400" style={{ width: `${Math.max((item.count / Math.max(kpi.totalTenants, 1)) * 100, 3)}%` }}/></div><span className="w-8 text-right text-sm tabular-nums text-slate-300">{item.count}</span></div>)}</div><div className="mt-6 border-t border-slate-800 pt-4"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Assinaturas por plano</p><div className="mt-3 flex flex-wrap gap-2">{data.planDistribution.length ? data.planDistribution.map((item) => <span key={item.name} className="rounded-lg bg-slate-800 px-3 py-2 text-xs text-slate-300">{item.name} <strong className="ml-1 text-white">{item.count}</strong></span>) : <span className="text-sm text-slate-500">Sem assinaturas ativas.</span>}</div></div></Card><Card className="p-5"><h2 className="font-semibold text-white">Ações rápidas</h2><p className="mt-1 text-xs text-slate-500">Acesse os fluxos operacionais mais usados.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><button className={buttonPrimary} onClick={() => navigate('/master/lojas')}>Cadastrar loja</button><button className={buttonSecondary} onClick={() => navigate('/master/financeiro')}>Criar fatura</button><button className={buttonSecondary} onClick={() => navigate('/master/planos')}>Criar plano</button></div></Card></section>
      <section className="grid gap-4 xl:grid-cols-2"><Card className="overflow-hidden"><div className="border-b border-slate-800 px-5 py-4"><h2 className="font-semibold text-white">Lojas com melhor desempenho</h2><p className="mt-1 text-xs text-slate-500">Ranking por GMV no período</p></div>{data.topStores.length ? <div className="divide-y divide-slate-800">{data.topStores.map((store, index) => <button key={store.tenantId} onClick={() => navigate(`/master/lojas/${store.tenantId}`)} className="grid w-full grid-cols-[32px_1fr_auto] items-center gap-3 px-5 py-3 text-left hover:bg-slate-800/40"><span className="text-sm font-bold text-slate-600">{String(index + 1).padStart(2, '0')}</span><span><strong className="block text-sm text-slate-200">{store.displayName}</strong><small className="text-slate-500">{integer(store.orders)} pedidos</small></span><strong className="text-sm tabular-nums text-white">{money(store.gmvCents)}</strong></button>)}</div> : <EmptyState/>}</Card><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-800 px-5 py-4"><div><h2 className="font-semibold text-white">Atenção necessária</h2><p className="mt-1 text-xs text-slate-500">Pendências que exigem decisão</p></div><AlertTriangle className="h-5 w-5 text-amber-300"/></div><div className="divide-y divide-slate-800">{data.attention.overdueInvoices.slice(0, 3).map((invoice) => <button key={invoice._id} onClick={() => navigate('/master/financeiro')} className="flex w-full items-center justify-between px-5 py-3 text-left hover:bg-slate-800/40"><span><strong className="block text-sm text-red-200">Fatura vencida</strong><small className="text-slate-500">{typeof invoice.tenantId === 'object' ? invoice.tenantId.displayName : invoice._id.slice(-8)}</small></span><span className="text-sm text-red-300">{money(invoice.amountCents)}</span></button>)}{data.attention.endingTrials.slice(0, 3).map((subscription) => <button key={subscription._id} onClick={() => navigate('/master/assinaturas')} className="flex w-full items-center justify-between px-5 py-3 text-left hover:bg-slate-800/40"><span><strong className="block text-sm text-cyan-200">Trial terminando</strong><small className="text-slate-500">{subscription.tenant?.displayName || 'Loja em trial'}</small></span><CalendarClock className="h-4 w-4 text-cyan-300"/></button>)}{!data.attention.overdueInvoices.length && !data.attention.endingTrials.length && !data.attention.stalledOnboarding.length && <EmptyState title="Tudo sob controle" description="Nenhuma pendência crítica foi encontrada."/>}</div></Card></section>
      <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-800 px-5 py-4"><div><h2 className="font-semibold text-white">Atividade recente</h2><p className="mt-1 text-xs text-slate-500">Ações administrativas auditadas</p></div><button onClick={() => navigate('/master/atividades')} className="text-sm font-medium text-[var(--pv-accent)] hover:text-amber-200">Ver todas</button></div><div className="divide-y divide-slate-800">{data.recentActivity.slice(0, 6).map((activity) => <div key={activity._id} className="flex items-start gap-3 px-5 py-3"><span className="mt-1 grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-slate-800 text-slate-400"><Users className="h-4 w-4"/></span><div className="min-w-0"><p className="truncate text-sm text-slate-200">{activity.action.replaceAll('_', ' ')}</p><p className="mt-1 text-xs text-slate-500">{activity.targetType || 'Plataforma'} · {new Date(activity.createdAt).toLocaleString('pt-BR')}</p></div></div>)}</div></Card></>}
  </div>;
}
