import { ArrowLeft, Clipboard, ExternalLink, Link2, Package, Pencil, ReceiptText, ShoppingBag, Users } from 'lucide-react';
import { useState } from 'react';
import { masterRequest, jsonInit } from '../api';
import { useRemote } from '../hooks';
import type { Tenant, TenantDetailResponse } from '../types';
import { date, integer, money } from '../utils';
import { Card, EmptyState, ErrorState, KpiCard, LoadingState, MiniAreaChart, Modal, PageHeader, StatusBadge, buttonPrimary, buttonSecondary, fieldClass } from '../components/MasterUI';

type Tab = 'resumo' | 'cobranca' | 'acessos' | 'atividade' | 'configuracao';
export default function MasterTenantDetail({ tenantId, navigate, notify }: { tenantId: string; navigate: (path: string) => void; notify: (tone: 'success' | 'error' | 'info', message: string) => void }) {
  const remote = useRemote(() => masterRequest<TenantDetailResponse>(`/tenants/${tenantId}`), [tenantId]); const [tab, setTab] = useState<Tab>('resumo'); const [editOpen, setEditOpen] = useState(false); const [slugOpen, setSlugOpen] = useState(false); const data = remote.data;
  if (remote.loading && !data) return <LoadingState rows={8}/>; if (remote.error || !data) return <ErrorState message={remote.error || 'Loja não encontrada.'} retry={remote.refresh}/>;
  const { tenant } = data;
  return <div className="space-y-6"><button className="flex items-center gap-2 text-sm text-slate-400 hover:text-white" onClick={() => navigate('/master/lojas')}><ArrowLeft className="h-4 w-4"/>Voltar para lojas</button><PageHeader eyebrow={`/${tenant.slug}`} title={tenant.displayName} description={`${tenant.legalName} · criada em ${date(tenant.createdAt)}`} actions={<><button className={buttonSecondary} onClick={() => { navigator.clipboard.writeText(`${window.location.origin}/${tenant.slug}`); notify('success', 'URL copiada.'); }}><Clipboard className="h-4 w-4"/>Copiar URL</button><button className={buttonSecondary} onClick={() => window.open(`/${tenant.slug}`, '_blank')}><ExternalLink className="h-4 w-4"/>Abrir vitrine</button><button className={buttonPrimary} onClick={() => setEditOpen(true)}><Pencil className="h-4 w-4"/>Editar</button></>}/><div className="flex flex-wrap items-center gap-2"><StatusBadge status={tenant.status}/>{data.subscription && <StatusBadge status={data.subscription.status}/>}<span className="text-sm text-slate-500">Responsável: {tenant.owner.name} · {tenant.owner.email}</span></div>
    <nav className="flex gap-1 overflow-x-auto border-b border-slate-800" aria-label="Seções da loja">{(['resumo', 'cobranca', 'acessos', 'atividade', 'configuracao'] as Tab[]).map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-medium ${tab === item ? 'border-emerald-400 text-emerald-300' : 'border-transparent text-slate-500 hover:text-white'}`}>{({ resumo: 'Resumo', cobranca: 'Assinatura e cobrança', acessos: 'Acessos', atividade: 'Atividade', configuracao: 'Configuração' } as Record<Tab, string>)[item]}</button>)}</nav>
    {tab === 'resumo' && <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Pedidos" value={integer(data.metrics.orders)} icon={<ShoppingBag className="h-5 w-5"/>}/><KpiCard label="GMV" value={money(data.metrics.gmvCents)} hint={`Ticket médio ${money(data.metrics.averageOrderCents)}`} icon={<ReceiptText className="h-5 w-5"/>}/><KpiCard label="Clientes" value={integer(data.metrics.customers)} icon={<Users className="h-5 w-5"/>}/><KpiCard label="Produtos" value={integer(data.metrics.products)} icon={<Package className="h-5 w-5"/>}/></section><div className="grid gap-4 xl:grid-cols-[1.5fr_1fr]"><Card className="p-5"><h2 className="font-semibold text-white">Pedidos e GMV da loja</h2><p className="mt-1 text-xs text-slate-500">Últimos 30 dias</p><MiniAreaChart points={data.orderSeries} valueKey="gmvCents"/></Card><Card className="p-5"><h2 className="font-semibold text-white">Dados cadastrais</h2><dl className="mt-5 space-y-4 text-sm"><Info label="Razão social" value={tenant.legalName}/><Info label="Responsável" value={tenant.owner.name}/><Info label="E-mail" value={tenant.owner.email}/><Info label="Telefone" value={tenant.owner.phone || 'Não informado'}/><Info label="Timezone" value={tenant.timezone}/></dl></Card></div></>}
    {tab === 'cobranca' && <div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><Card className="p-5"><h2 className="font-semibold text-white">Assinatura atual</h2>{data.subscription ? <dl className="mt-5 space-y-4 text-sm"><Info label="Plano" value={data.subscription.plan?.name || 'Plano vinculado'}/><Info label="Valor" value={money(data.subscription.plan?.priceCents || 0)}/><Info label="Periodicidade" value={data.subscription.plan?.interval === 'yearly' ? 'Anual' : 'Mensal'}/><Info label="Período atual" value={`${date(data.subscription.currentPeriodStart)} a ${date(data.subscription.currentPeriodEnd)}`}/><Info label="Fim do trial" value={date(data.subscription.trialEndsAt)}/></dl> : <EmptyState title="Sem assinatura" description="Esta loja ainda não possui assinatura vinculada."/>}</Card><Card className="overflow-hidden"><div className="border-b border-slate-800 px-5 py-4"><h2 className="font-semibold text-white">Histórico de faturas</h2></div>{data.invoices.length ? <div className="divide-y divide-slate-800">{data.invoices.map((invoice) => <div key={invoice._id} className="grid grid-cols-[1fr_auto] gap-4 px-5 py-4"><div><div className="flex items-center gap-2"><StatusBadge status={invoice.status}/><span className="text-sm font-semibold text-white">{money(invoice.amountCents)}</span></div><p className="mt-2 text-xs text-slate-500">Vencimento {date(invoice.dueAt)}{invoice.receiptReference ? ` · ref. ${invoice.receiptReference}` : ''}</p></div><span className="text-xs text-slate-500">#{invoice._id.slice(-8)}</span></div>)}</div> : <EmptyState title="Sem faturas"/>}</Card></div>}
    {tab === 'acessos' && <div className="grid gap-4 xl:grid-cols-2"><Card className="overflow-hidden"><div className="border-b border-slate-800 px-5 py-4"><h2 className="font-semibold text-white">Membros da loja</h2></div>{data.memberships.length ? <div className="divide-y divide-slate-800">{data.memberships.map((item) => <div key={item._id} className="flex items-center justify-between gap-3 px-5 py-4"><div><strong className="text-sm text-slate-200">{item.accountId.name}</strong><p className="text-xs text-slate-500">{item.accountId.email} · {item.role}</p></div><StatusBadge status={item.active ? 'active' : 'cancelled'}/></div>)}</div> : <EmptyState title="Nenhum membro"/>}</Card><Card className="overflow-hidden"><div className="border-b border-slate-800 px-5 py-4"><h2 className="font-semibold text-white">Convites</h2></div>{data.invitations.length ? <div className="divide-y divide-slate-800">{data.invitations.map((item) => <div key={item._id} className="px-5 py-4"><div className="flex items-center justify-between"><strong className="text-sm text-slate-200">{item.email}</strong><StatusBadge status={item.acceptedAt ? 'active' : item.revokedAt ? 'cancelled' : 'pending'}/></div><p className="mt-1 text-xs text-slate-500">{item.role} · expira em {date(item.expiresAt)}</p></div>)}</div> : <EmptyState title="Sem convites"/>}</Card></div>}
    {tab === 'atividade' && <Card className="overflow-hidden">{data.activities.length ? <div className="divide-y divide-slate-800">{data.activities.map((activity) => <div key={activity._id} className="flex gap-4 px-5 py-4"><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-emerald-400 ring-4 ring-emerald-400/10"/><div><strong className="text-sm text-slate-200">{activity.action.replaceAll('_', ' ')}</strong><p className="mt-1 text-xs text-slate-500">{activity.targetType} · {date(activity.createdAt, true)}</p>{activity.reason && <p className="mt-2 text-sm text-slate-400">{activity.reason}</p>}</div></div>)}</div> : <EmptyState title="Sem atividade registrada"/>}</Card>}
    {tab === 'configuracao' && <Card className="p-5"><h2 className="font-semibold text-white">Configuração da plataforma</h2><p className="mt-2 text-sm text-slate-400">Dados operacionais controlados pelo Master. Conteúdo e identidade da vitrine continuam no painel da loja.</p><div className="mt-5 flex flex-wrap gap-2"><button className={buttonPrimary} onClick={() => setEditOpen(true)}>Editar dados cadastrais</button><button className={buttonSecondary} onClick={() => setSlugOpen(true)}><Link2 className="h-4 w-4"/>Alterar slug</button></div><div className="mt-5 rounded-xl border border-slate-800 bg-slate-950 p-4"><p className="text-xs text-slate-500">URL pública atual</p><p className="mt-1 break-all font-mono text-sm text-slate-200">{window.location.origin}/{tenant.slug}</p><p className="mt-2 text-xs text-slate-500">Ao alterar, o endereço anterior é preservado no histórico de redirecionamento.</p></div></Card>}
    <EditTenantModal key={editOpen ? tenant.updatedAt || tenant._id : 'edit-closed'} tenant={tenant} open={editOpen} onClose={() => setEditOpen(false)} onSaved={() => { setEditOpen(false); remote.refresh(); notify('success', 'Dados da loja atualizados.'); }}/>
    <SlugModal key={slugOpen ? tenant.slug : 'slug-closed'} tenant={tenant} open={slugOpen} onClose={() => setSlugOpen(false)} onSaved={() => { setSlugOpen(false); remote.refresh(); notify('success', 'Slug atualizado e endereço anterior preservado.'); }}/>
  </div>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-4 border-b border-slate-800 pb-3 last:border-0"><dt className="text-slate-500">{label}</dt><dd className="text-right text-slate-200">{value}</dd></div>; }
function EditTenantModal({ tenant, open, onClose, onSaved }: { tenant: Tenant; open: boolean; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState({ legalName: tenant.legalName, displayName: tenant.displayName, owner: { ...tenant.owner, phone: tenant.owner.phone || '' }, timezone: tenant.timezone }); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const save = async () => { setBusy(true); setError(''); try { await masterRequest(`/tenants/${tenant._id}`, jsonInit('PATCH', form)); onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao salvar.'); } finally { setBusy(false); } };
  return <Modal open={open} onClose={onClose} title="Editar loja" footer={<><button className={buttonSecondary} onClick={onClose}>Cancelar</button><button className={buttonPrimary} disabled={busy} onClick={save}>{busy ? 'Salvando...' : 'Salvar alterações'}</button></>}><div className="grid gap-4 sm:grid-cols-2"><EditField label="Razão social" value={form.legalName} onChange={(value) => setForm({ ...form, legalName: value })}/><EditField label="Nome fantasia" value={form.displayName} onChange={(value) => setForm({ ...form, displayName: value })}/><EditField label="Responsável" value={form.owner.name} onChange={(value) => setForm({ ...form, owner: { ...form.owner, name: value } })}/><EditField label="E-mail" value={form.owner.email} onChange={(value) => setForm({ ...form, owner: { ...form.owner, email: value } })}/><EditField label="Telefone" value={form.owner.phone} onChange={(value) => setForm({ ...form, owner: { ...form.owner, phone: value } })}/><EditField label="Timezone" value={form.timezone} onChange={(value) => setForm({ ...form, timezone: value })}/></div>{error && <p className="mt-4 text-sm text-red-300">{error}</p>}</Modal>;
}
function EditField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-sm text-slate-300">{label}<input className={`${fieldClass} mt-2`} value={value} onChange={(event) => onChange(event.target.value)}/></label>; }

function SlugModal({ tenant, open, onClose, onSaved }: { tenant: Tenant; open: boolean; onClose: () => void; onSaved: () => void }) {
  const [slug, setSlug] = useState(tenant.slug);
  const [reason, setReason] = useState('Ajuste de endereço autorizado pelo Admin Master');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const normalized = slug.toLowerCase().trim().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
  const save = async () => {
    if (normalized.length < 3 || reason.trim().length < 5) { setError('Informe um slug e um motivo válidos.'); return; }
    setBusy(true); setError('');
    try { await masterRequest(`/tenants/${tenant._id}/slug`, jsonInit('PATCH', { slug: normalized, reason })); onSaved(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha ao alterar slug.'); }
    finally { setBusy(false); }
  };
  return <Modal open={open} onClose={onClose} title="Alterar slug da loja" description="O endereço anterior continuará redirecionando para a loja." footer={<><button className={buttonSecondary} onClick={onClose}>Cancelar</button><button className={buttonPrimary} disabled={busy || normalized === tenant.slug} onClick={save}>{busy ? 'Alterando...' : 'Confirmar novo slug'}</button></>}><div className="space-y-4"><label className="text-sm text-slate-300">Novo slug<input className={`${fieldClass} mt-2 font-mono`} value={slug} onChange={(event) => setSlug(event.target.value)}/><span className="mt-2 block break-all text-xs text-slate-500">{window.location.origin}/{normalized || 'novo-slug'}</span></label><label className="text-sm text-slate-300">Motivo<input className={`${fieldClass} mt-2`} value={reason} minLength={5} onChange={(event) => setReason(event.target.value)}/></label>{error && <p className="text-sm text-red-300">{error}</p>}</div></Modal>;
}
