import { Copy, Layers3, Pencil, Plus, Power } from 'lucide-react';
import { useState } from 'react';
import { jsonInit, masterRequest } from '../api';
import { useRemote } from '../hooks';
import type { ListResponse, Plan } from '../types';
import { date, money } from '../utils';
import { Card, EmptyState, ErrorState, LoadingState, Modal, PageHeader, StatusBadge, buttonPrimary, buttonSecondary, fieldClass } from '../components/MasterUI';

export default function MasterPlans({ notify }: { notify: (tone: 'success' | 'error' | 'info', message: string) => void }) {
  const remote = useRemote(() => masterRequest<ListResponse<Plan>>('/plans?limit=100'), []); const [editing, setEditing] = useState<Plan | 'new' | null>(null); const [busyId, setBusyId] = useState('');
  const mutate = async (plan: Plan, action: 'duplicate' | 'status') => { setBusyId(plan._id); try { if (action === 'duplicate') await masterRequest(`/plans/${plan._id}/duplicate`, { method: 'POST' }); else await masterRequest(`/plans/${plan._id}/status`, jsonInit('PATCH', { active: !plan.active })); notify('success', action === 'duplicate' ? 'Plano duplicado.' : 'Disponibilidade do plano atualizada.'); remote.refresh(); } catch (error) { notify('error', error instanceof Error ? error.message : 'Falha na operação.'); } finally { setBusyId(''); } };
  return <div className="space-y-6"><PageHeader eyebrow="Oferta comercial" title="Planos" description="Configure preços, trials, limites e recursos. Faturas já emitidas preservam seus valores históricos." actions={<button className={buttonPrimary} onClick={() => setEditing('new')}><Plus className="h-4 w-4"/>Novo plano</button>}/>{remote.loading && !remote.data ? <LoadingState rows={5}/> : remote.error ? <ErrorState message={remote.error} retry={remote.refresh}/> : <div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{remote.data?.items.map((plan) => <Card key={plan._id} className="flex flex-col p-5"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-400/10 text-emerald-400"><Layers3 className="h-5 w-5"/></span><StatusBadge status={plan.active ? 'active' : 'cancelled'}/></div><div className="mt-5"><h2 className="text-lg font-semibold text-white">{plan.name}</h2><p className="mt-1 font-mono text-xs text-slate-500">{plan.code}</p><p className="mt-5 text-3xl font-bold text-white">{money(plan.priceCents)}<span className="text-sm font-normal text-slate-500">/{plan.interval === 'yearly' ? 'ano' : 'mês'}</span></p><p className="mt-2 text-sm text-slate-400">Trial de {plan.trialDays} dia(s) · {plan.activeSubscriptions || 0} assinatura(s) ativa(s)</p></div><div className="mt-5 grid grid-cols-2 gap-3 border-y border-slate-800 py-4"><div><p className="text-xs text-slate-500">Recursos ativos</p><strong className="mt-1 block text-slate-200">{Object.values(plan.features || {}).filter(Boolean).length}</strong></div><div><p className="text-xs text-slate-500">Limites</p><strong className="mt-1 block text-slate-200">{Object.keys(plan.limits || {}).length}</strong></div></div><p className="mt-4 text-xs text-slate-600">Atualizado em {date(plan.updatedAt || plan.createdAt)}</p><div className="mt-auto flex gap-2 pt-5"><button className={`${buttonSecondary} flex-1`} onClick={() => setEditing(plan)}><Pencil className="h-4 w-4"/>Editar</button><button disabled={busyId === plan._id} className={buttonSecondary} onClick={() => mutate(plan, 'duplicate')} title="Duplicar"><Copy className="h-4 w-4"/></button><button disabled={busyId === plan._id} className={buttonSecondary} onClick={() => mutate(plan, 'status')} title={plan.active ? 'Desativar' : 'Ativar'}><Power className="h-4 w-4"/></button></div></Card>)}{!remote.data?.items.length && <div className="lg:col-span-2"><EmptyState title="Nenhum plano criado" action={<button className={buttonPrimary} onClick={() => setEditing('new')}>Criar primeiro plano</button>}/></div>}</div>}<PlanModal key={editing === 'new' ? 'new' : editing?._id || 'closed'} plan={editing === 'new' ? null : editing} open={editing !== null} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); remote.refresh(); notify('success', editing === 'new' ? 'Plano criado.' : 'Plano atualizado.'); }}/></div>;
}
function PlanModal({ plan, open, onClose, onSaved }: { plan: Plan | null; open: boolean; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState(() => ({ name: plan?.name || '', code: plan?.code || '', price: plan ? String(plan.priceCents / 100) : '', interval: plan?.interval || 'monthly', trialDays: String(plan?.trialDays || 0), features: Object.entries(plan?.features || {}).map(([key, value]) => `${key}:${value}`).join('\n'), limits: Object.entries(plan?.limits || {}).map(([key, value]) => `${key}:${value}`).join('\n') })); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const parseFeatures = () => Object.fromEntries(form.features.split('\n').map((line) => line.trim()).filter(Boolean).map((line) => { const [key, value] = line.split(':'); return [key.trim(), value?.trim() !== 'false']; })); const parseLimits = () => Object.fromEntries(form.limits.split('\n').map((line) => line.trim()).filter(Boolean).map((line) => { const [key, value] = line.split(':'); return [key.trim(), Number(value) || 0]; }));
  const save = async () => { setBusy(true); setError(''); const body = { name: form.name, ...(plan ? {} : { code: form.code.toLowerCase().replace(/[^a-z0-9_-]/g, '-') }), priceCents: Math.round(Number(form.price.replace(',', '.')) * 100), interval: form.interval, trialDays: Number(form.trialDays), features: parseFeatures(), limits: parseLimits() }; try { await masterRequest(plan ? `/plans/${plan._id}` : '/plans', jsonInit(plan ? 'PATCH' : 'POST', body)); onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao salvar plano.'); } finally { setBusy(false); } };
  return <Modal open={open} onClose={onClose} title={plan ? 'Editar plano' : 'Novo plano'} description="Use uma linha por recurso ou limite no formato nome:valor." footer={<><button className={buttonSecondary} onClick={onClose}>Cancelar</button><button className={buttonPrimary} disabled={busy} onClick={save}>{busy ? 'Salvando...' : 'Salvar plano'}</button></>}><div className="grid gap-4 sm:grid-cols-2"><PlanField label="Nome" value={form.name} onChange={(value) => setForm({ ...form, name: value })}/><PlanField label="Código" disabled={Boolean(plan)} value={form.code} onChange={(value) => setForm({ ...form, code: value })}/><PlanField label="Preço em R$" value={form.price} onChange={(value) => setForm({ ...form, price: value })}/><label className="text-sm text-slate-300">Periodicidade<select className={`${fieldClass} mt-2`} value={form.interval} onChange={(event) => setForm({ ...form, interval: event.target.value as 'monthly' | 'yearly' })}><option value="monthly">Mensal</option><option value="yearly">Anual</option></select></label><PlanField label="Dias de trial" value={form.trialDays} onChange={(value) => setForm({ ...form, trialDays: value })}/><label className="text-sm text-slate-300 sm:col-span-2">Features<textarea className={`${fieldClass} mt-2 h-28 py-3 font-mono`} value={form.features} onChange={(event) => setForm({ ...form, features: event.target.value })} placeholder={'pedidos:true\nfidelidade:true'}/></label><label className="text-sm text-slate-300 sm:col-span-2">Limites<textarea className={`${fieldClass} mt-2 h-28 py-3 font-mono`} value={form.limits} onChange={(event) => setForm({ ...form, limits: event.target.value })} placeholder={'produtos:100\nusuarios:5'}/></label></div>{error && <p className="mt-4 text-sm text-red-300">{error}</p>}</Modal>;
}
function PlanField({ label, value, onChange, disabled }: { label: string; value: string; onChange: (value: string) => void; disabled?: boolean }) { return <label className="text-sm text-slate-300">{label}<input disabled={disabled} className={`${fieldClass} mt-2`} value={value} onChange={(event) => onChange(event.target.value)}/></label>; }
